# Generated by Django 5.1 on 2024-08-13 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx10m', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdatatest',
            name='education',
            field=models.CharField(choices=[('Bachelors', 'Bachelors'), ('Some-college', 'Some-college'), ('11th', '11th'), ('HS-grad', 'HS-grad'), ('Prof-school', 'Prof-school'), ('Assoc-acdm', 'Assoc-acdm'), ('Assoc-voc', 'Assoc-voc'), ('9th', '9th'), ('7th-8th', '7th-8th'), ('12th', '12th'), ('Masters', 'Masters'), ('1st-4th', '1st-4th'), ('10th', '10th'), ('Doctorate', 'Doctorate'), ('5th-6th', '5th-6th'), ('Preschool', 'Preschool')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdatatest',
            name='native_country',
            field=models.CharField(blank=True, choices=[('United-States', 'United-States'), ('Cambodia', 'Cambodia'), ('England', 'England'), ('Puerto-Rico', 'Puerto-Rico'), ('Canada', 'Canada'), ('Germany', 'Germany'), ('Outlying-US(Guam-USVI-etc)', 'Outlying-US(Guam-USVI-etc)'), ('India', 'India'), ('Japan', 'Japan'), ('Greece', 'Greece'), ('South', 'South'), ('China', 'China'), ('Cuba', 'Cuba'), ('Iran', 'Iran'), ('Honduras', 'Honduras'), ('Philippines', 'Philippines'), ('Italy', 'Italy'), ('Poland', 'Poland'), ('Jamaica', 'Jamaica'), ('Vietnam', 'Vietnam'), ('Mexico', 'Mexico'), ('Portugal', 'Portugal'), ('Ireland', 'Ireland'), ('France', 'France'), ('Dominican-Republic', 'Dominican-Republic'), ('Laos', 'Laos'), ('Ecuador', 'Ecuador'), ('Taiwan', 'Taiwan'), ('Haiti', 'Haiti'), ('Columbia', 'Columbia'), ('Hungary', 'Hungary'), ('Guatemala', 'Guatemala'), ('Nicaragua', 'Nicaragua'), ('Scotland', 'Scotland'), ('Thailand', 'Thailand'), ('Yugoslavia', 'Yugoslavia'), ('El-Salvador', 'El-Salvador'), ('Trinadad&Tobago', 'Trinadad&Tobago'), ('Peru', 'Peru'), ('Hong', 'Hong'), ('Holand-Netherlands', 'Holand-Netherlands')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdatatest',
            name='occupation',
            field=models.CharField(blank=True, choices=[('Tech-support', 'Tech-support'), ('Craft-repair', 'Craft-repair'), ('Other-service', 'Other-service'), ('Sales', 'Sales'), ('Exec-managerial', 'Exec-managerial'), ('Prof-specialty', 'Prof-specialty'), ('Handlers-cleaners', 'Handlers-cleaners'), ('Machine-op-inspct', 'Machine-op-inspct'), ('Adm-clerical', 'Adm-clerical'), ('Farming-fishing', 'Farming-fishing'), ('Transport-moving', 'Transport-moving'), ('Priv-house-serv', 'Priv-house-serv'), ('Protective-serv', 'Protective-serv'), ('Armed-Forces', 'Armed-Forces')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdatatest',
            name='race',
            field=models.CharField(choices=[('White', 'White'), ('Asian-Pac-Islander', 'Asian-Pac-Islander'), ('Amer-Indian-Eskimo', 'Amer-Indian-Eskimo'), ('Other', 'Other'), ('Black', 'Black')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdatatest',
            name='relationship',
            field=models.CharField(choices=[('Wife', 'Wife'), ('Own-child', 'Own-child'), ('Husband', 'Husband'), ('Not-in-family', 'Not-in-family'), ('Other-relative', 'Other-relative'), ('Unmarried', 'Unmarried')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdatatest',
            name='sex',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdatatest',
            name='workclass',
            field=models.CharField(blank=True, choices=[('Private', 'Private'), ('Self-emp-not-inc', 'Self-emp-not-inc'), ('Self-emp-inc', 'Self-emp-inc'), ('Federal-gov', 'Federal-gov'), ('Local-gov', 'Local-gov'), ('State-gov', 'State-gov'), ('Without-pay', 'Without-pay'), ('Never-worked', 'Never-worked')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demographicdatatest',
            name='income',
            field=models.CharField(choices=[('>50K', '>50K'), ('<=50K', '<=50K')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='demographicdatatest',
            name='marital_status',
            field=models.CharField(choices=[('Married-civ-spouse', 'Married-civ-spouse'), ('Divorced', 'Divorced'), ('Never-married', 'Never-married'), ('Separated', 'Separated'), ('Widowed', 'Widowed'), ('Married-spouse-absent', 'Married-spouse-absent'), ('Married-AF-spouse', 'Married-AF-spouse')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='NativeCountry',
        ),
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.DeleteModel(
            name='Race',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
        migrations.DeleteModel(
            name='Sex',
        ),
        migrations.DeleteModel(
            name='WorkClass',
        ),
    ]
