# Generated by Django 5.1 on 2024-08-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx10m', '0003_education_nativecountry_occupation_race_relationship_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='nativecountry',
            name='label',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='label',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='label',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='sex',
            name='label',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='workclass',
            name='label',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
