# Generated by Django 5.1 on 2024-08-15 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx10m', '0005_alter_nativecountry_label_alter_sex_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='marital_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marital_status', to='crudx10m.maritalstatus'),
        ),
    ]
