# Generated by Django 5.1 on 2024-08-15 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudx10m', '0007_alter_maritalstatus_label'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemographicData',
        ),
    ]
