# Generated by Django 5.1 on 2024-08-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudx10m', '0009_demographicdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemographicData',
        ),
    ]
