# Generated by Django 5.1 on 2024-08-15 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudx10m', '0010_delete_demographicdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemographicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('fnlwgt', models.IntegerField()),
                ('education_num', models.IntegerField()),
                ('capital_gain', models.IntegerField()),
                ('capital_loss', models.IntegerField()),
                ('hours_per_week', models.IntegerField()),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education', to='crudx10m.education')),
                ('marital_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marital_status', to='crudx10m.maritalstatus')),
                ('native_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudx10m.nativecountry')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='crudx10m.occupation')),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race', to='crudx10m.race')),
                ('relationship', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crudx10m.relationship')),
                ('sex', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sex', to='crudx10m.sex')),
                ('workclass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workclasses', to='crudx10m.workclass')),
            ],
        ),
    ]
