# Generated by Django 4.1.13 on 2024-08-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='ArtistId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
